adapter_config: &adapter_config
  adapter: mysql2
  encoding: utf8
  database: demo_app
  host: localhost
  pool: 5
  timeout: 5000

production:
  <<: *adapter_config
  username: root
  password: root

development:
  <<: *adapter_config
  username: root
  password: root